-- MySQL Script generated by MySQL Workbench
-- 08/03/15 01:13:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema discussion_website
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema discussion_website
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `discussion_website` DEFAULT CHARACTER SET utf8 COLLATE utf8_czech_ci ;
USE `discussion_website` ;

-- -----------------------------------------------------
-- Table `discussion_website`.`ip_addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discussion_website`.`ip_addresses` ;

CREATE TABLE IF NOT EXISTS `discussion_website`.`ip_addresses` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '',
  `ip` BINARY(16) NOT NULL COMMENT '',
  `role` ENUM('verified','normal','supervised','banned') CHARACTER SET 'utf8' COLLATE 'utf8_czech_ci' NOT NULL DEFAULT 'normal' COMMENT '',
  `ban_message` TEXT NULL DEFAULT NULL COMMENT '',
  `ban_time` TIMESTAMP NULL DEFAULT NULL COMMENT '',
  `total_ban` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `ip_UNIQUE` (`ip` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_czech_ci;


-- -----------------------------------------------------
-- Table `discussion_website`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discussion_website`.`users` ;

CREATE TABLE IF NOT EXISTS `discussion_website`.`users` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '',
  `ip_id` INT(10) NULL COMMENT '',
  `photo_id` INT(10) NULL DEFAULT NULL COMMENT '',
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_czech_ci' NOT NULL COMMENT '',
  `password` CHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_czech_ci' NOT NULL COMMENT '',
  `password_token` CHAR(128) CHARACTER SET 'utf8' COLLATE 'utf8_czech_ci' NULL DEFAULT NULL COMMENT '',
  `password_token_validity` TIMESTAMP NULL DEFAULT NULL COMMENT '',
  `nickname` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_czech_ci' NOT NULL COMMENT '',
  `gender` ENUM('male','female') CHARACTER SET 'utf8' COLLATE 'utf8_czech_ci' NOT NULL COMMENT '',
  `birthdate` DATE NOT NULL COMMENT '',
  `role` ENUM('administrator','verified','normal','supervised','banned') CHARACTER SET 'utf8' COLLATE 'utf8_czech_ci' NOT NULL DEFAULT 'normal' COMMENT '',
  `activated` TINYINT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '',
  `ban_message` TEXT NULL DEFAULT NULL COMMENT '',
  `ban_time` TIMESTAMP NULL DEFAULT NULL COMMENT '',
  `token_resend_blocked` TIMESTAMP NULL DEFAULT NULL COMMENT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `e-mail_UNIQUE` (`email` ASC)  COMMENT '',
  UNIQUE INDEX `name_UNIQUE` (`nickname` ASC)  COMMENT '',
  INDEX `fk_users_photos1_idx` (`photo_id` ASC)  COMMENT '',
  INDEX `fk_users_ip_addresses1_idx` (`ip_id` ASC)  COMMENT '',
  CONSTRAINT `fk_users_photos1`
    FOREIGN KEY (`photo_id`)
    REFERENCES `discussion_website`.`user_images` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_users_ip_addresses1`
    FOREIGN KEY (`ip_id`)
    REFERENCES `discussion_website`.`ip_addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_czech_ci;


-- -----------------------------------------------------
-- Table `discussion_website`.`user_images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discussion_website`.`user_images` ;

CREATE TABLE IF NOT EXISTS `discussion_website`.`user_images` (
  `user_id` INT(10) NOT NULL COMMENT '',
  `id` INT(10) NOT NULL COMMENT '',
  `name` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_czech_ci' NOT NULL COMMENT '',
  `approved` TINYINT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '',
  `showed` TINYINT(4) UNSIGNED NOT NULL DEFAULT '1' COMMENT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`, `user_id`)  COMMENT '',
  INDEX `fk_photos_users1_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_photos_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `discussion_website`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_czech_ci;


-- -----------------------------------------------------
-- Table `discussion_website`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discussion_website`.`categories` ;

CREATE TABLE IF NOT EXISTS `discussion_website`.`categories` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_czech_ci' NOT NULL COMMENT '',
  `description` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_czech_ci' NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `desc_UNIQUE` (`description` ASC)  COMMENT '',
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_czech_ci;


-- -----------------------------------------------------
-- Table `discussion_website`.`posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discussion_website`.`posts` ;

CREATE TABLE IF NOT EXISTS `discussion_website`.`posts` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '',
  `category_id` INT(10) NOT NULL COMMENT '',
  `ip_id` INT(10) NULL COMMENT '',
  `user_id` INT(10) NULL DEFAULT NULL COMMENT '',
  `title` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_czech_ci' NOT NULL COMMENT '',
  `content` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_czech_ci' NOT NULL COMMENT '',
  `nickname` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_czech_ci' NULL DEFAULT NULL COMMENT '',
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_czech_ci' NULL DEFAULT NULL COMMENT '',
  `gender` ENUM('male','female') CHARACTER SET 'utf8' COLLATE 'utf8_czech_ci' NULL DEFAULT NULL COMMENT '',
  `age` TINYINT(3) UNSIGNED NULL DEFAULT NULL COMMENT '',
  `approved` TINYINT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '',
  `showed` TINYINT(4) UNSIGNED NOT NULL DEFAULT '1' COMMENT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_posts_users1_idx` (`user_id` ASC)  COMMENT '',
  INDEX `fk_posts_ip_addresses1_idx` (`ip_id` ASC)  COMMENT '',
  INDEX `fk_posts_categories1_idx` (`category_id` ASC)  COMMENT '',
  CONSTRAINT `fk_posts_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `discussion_website`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_posts_ip_addresses1`
    FOREIGN KEY (`ip_id`)
    REFERENCES `discussion_website`.`ip_addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_posts_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `discussion_website`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_czech_ci;


-- -----------------------------------------------------
-- Table `discussion_website`.`post_views`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discussion_website`.`post_views` ;

CREATE TABLE IF NOT EXISTS `discussion_website`.`post_views` (
  `post_id` INT(10) NOT NULL COMMENT '',
  `ip_id` INT(10) NOT NULL COMMENT '',
  PRIMARY KEY (`post_id`, `ip_id`)  COMMENT '',
  INDEX `fk_post_views_ip_addresses1_idx` (`ip_id` ASC)  COMMENT '',
  CONSTRAINT `fk_post_views_posts1`
    FOREIGN KEY (`post_id`)
    REFERENCES `discussion_website`.`posts` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_post_views_ip_addresses1`
    FOREIGN KEY (`ip_id`)
    REFERENCES `discussion_website`.`ip_addresses` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `discussion_website`.`post_reports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discussion_website`.`post_reports` ;

CREATE TABLE IF NOT EXISTS `discussion_website`.`post_reports` (
  `post_id` INT(10) NOT NULL COMMENT '',
  `user_id` INT(10) NOT NULL COMMENT '',
  `content` VARCHAR(255) NOT NULL COMMENT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`post_id`, `user_id`)  COMMENT '',
  INDEX `fk_post_reports_posts1_idx` (`post_id` ASC)  COMMENT '',
  INDEX `fk_post_reports_users1_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_post_reports_posts1`
    FOREIGN KEY (`post_id`)
    REFERENCES `discussion_website`.`posts` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_post_reports_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `discussion_website`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `discussion_website`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discussion_website`.`comments` ;

CREATE TABLE IF NOT EXISTS `discussion_website`.`comments` (
  `post_id` INT(10) NOT NULL COMMENT '',
  `id` INT(10) NOT NULL COMMENT '',
  `ip_id` INT(10) NULL COMMENT '',
  `user_id` INT(10) NULL COMMENT '',
  `parent_post_id` INT(10) NULL COMMENT '',
  `parent_id` INT(10) NULL COMMENT '',
  `content` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_czech_ci' NOT NULL COMMENT '',
  `nickname` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_czech_ci' NULL DEFAULT NULL COMMENT '',
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_czech_ci' NULL DEFAULT NULL COMMENT '',
  `gender` ENUM('male','female') CHARACTER SET 'utf8' COLLATE 'utf8_czech_ci' NULL COMMENT '',
  `age` TINYINT(3) UNSIGNED NULL DEFAULT NULL COMMENT '',
  `approved` TINYINT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '',
  `showed` TINYINT(4) UNSIGNED NOT NULL DEFAULT '1' COMMENT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`post_id`, `id`)  COMMENT '',
  INDEX `fk_comments_posts1_idx` (`post_id` ASC)  COMMENT '',
  INDEX `fk_comments_ip_addresses1_idx` (`ip_id` ASC)  COMMENT '',
  INDEX `fk_comments_users1_idx` (`user_id` ASC)  COMMENT '',
  INDEX `fk_comments_comments1_idx` (`parent_post_id` ASC, `parent_id` ASC)  COMMENT '',
  CONSTRAINT `fk_comments_posts1`
    FOREIGN KEY (`post_id`)
    REFERENCES `discussion_website`.`posts` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comments_ip_addresses1`
    FOREIGN KEY (`ip_id`)
    REFERENCES `discussion_website`.`ip_addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `discussion_website`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comments_comments1`
    FOREIGN KEY (`parent_post_id` , `parent_id`)
    REFERENCES `discussion_website`.`comments` (`post_id` , `id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_czech_ci;


-- -----------------------------------------------------
-- Table `discussion_website`.`comment_reports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discussion_website`.`comment_reports` ;

CREATE TABLE IF NOT EXISTS `discussion_website`.`comment_reports` (
  `post_id` INT(10) NOT NULL COMMENT '',
  `comment_id` INT(10) NOT NULL COMMENT '',
  `user_id` INT(10) NOT NULL COMMENT '',
  `content` VARCHAR(255) NOT NULL COMMENT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`post_id`, `comment_id`, `user_id`)  COMMENT '',
  INDEX `fk_post_reports_users1_idx` (`user_id` ASC)  COMMENT '',
  INDEX `fk_comment_reports_comments1_idx` (`post_id` ASC, `comment_id` ASC)  COMMENT '',
  CONSTRAINT `fk_post_reports_users10`
    FOREIGN KEY (`user_id`)
    REFERENCES `discussion_website`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comment_reports_comments1`
    FOREIGN KEY (`post_id` , `comment_id`)
    REFERENCES `discussion_website`.`comments` (`post_id` , `id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `discussion_website`.`invitations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discussion_website`.`invitations` ;

CREATE TABLE IF NOT EXISTS `discussion_website`.`invitations` (
  `inviting_id` INT(10) NOT NULL COMMENT '',
  `invited_id` INT(10) NOT NULL COMMENT '',
  `post_id` INT(10) NOT NULL COMMENT '',
  PRIMARY KEY (`inviting_id`, `invited_id`, `post_id`)  COMMENT '',
  INDEX `fk_invitations_users2_idx` (`invited_id` ASC)  COMMENT '',
  INDEX `fk_invitations_posts1_idx` (`post_id` ASC)  COMMENT '',
  CONSTRAINT `fk_invitations_users1`
    FOREIGN KEY (`inviting_id`)
    REFERENCES `discussion_website`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invitations_users2`
    FOREIGN KEY (`invited_id`)
    REFERENCES `discussion_website`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invitations_posts1`
    FOREIGN KEY (`post_id`)
    REFERENCES `discussion_website`.`posts` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `discussion_website`.`comment_votes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discussion_website`.`comment_votes` ;

CREATE TABLE IF NOT EXISTS `discussion_website`.`comment_votes` (
  `user_id` INT(10) NOT NULL COMMENT '',
  `post_id` INT(10) NOT NULL COMMENT '',
  `comment_id` INT(10) NOT NULL COMMENT '',
  `vote` ENUM('like','hate') CHARACTER SET 'utf8' COLLATE 'utf8_czech_ci' NOT NULL COMMENT '',
  PRIMARY KEY (`user_id`, `post_id`, `comment_id`)  COMMENT '',
  INDEX `fk_comment_votes_users1_idx` (`user_id` ASC)  COMMENT '',
  INDEX `fk_comment_votes_comments1_idx` (`post_id` ASC, `comment_id` ASC)  COMMENT '',
  CONSTRAINT `fk_comment_votes_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `discussion_website`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comment_votes_comments1`
    FOREIGN KEY (`post_id` , `comment_id`)
    REFERENCES `discussion_website`.`comments` (`post_id` , `id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_czech_ci;


-- -----------------------------------------------------
-- Table `discussion_website`.`forbidden_keywords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discussion_website`.`forbidden_keywords` ;

CREATE TABLE IF NOT EXISTS `discussion_website`.`forbidden_keywords` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '',
  `keyword` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_czech_ci' NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `word_UNIQUE` (`keyword` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_czech_ci;


-- -----------------------------------------------------
-- Table `discussion_website`.`messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discussion_website`.`messages` ;

CREATE TABLE IF NOT EXISTS `discussion_website`.`messages` (
  `recipient_id` INT(10) NOT NULL COMMENT '',
  `id` INT(10) NOT NULL COMMENT '',
  `ip_id` INT(10) NULL COMMENT '',
  `sender_id` INT(10) NULL DEFAULT NULL COMMENT '',
  `content` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_czech_ci' NOT NULL COMMENT '',
  `nickname` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_czech_ci' NULL DEFAULT NULL COMMENT '',
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_czech_ci' NULL DEFAULT NULL COMMENT '',
  `gender` ENUM('male','female') CHARACTER SET 'utf8' COLLATE 'utf8_czech_ci' NULL DEFAULT NULL COMMENT '',
  `age` TINYINT(3) UNSIGNED NULL DEFAULT NULL COMMENT '',
  `approved` TINYINT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '',
  `showed` TINYINT(4) UNSIGNED NOT NULL DEFAULT '1' COMMENT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`recipient_id`, `id`)  COMMENT '',
  INDEX `fk_messages_users2_idx` (`sender_id` ASC)  COMMENT '',
  INDEX `fk_messages_users1_idx` (`recipient_id` ASC)  COMMENT '',
  INDEX `fk_messages_ip_addresses1_idx` (`ip_id` ASC)  COMMENT '',
  CONSTRAINT `fk_messages_users1`
    FOREIGN KEY (`recipient_id`)
    REFERENCES `discussion_website`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_messages_users2`
    FOREIGN KEY (`sender_id`)
    REFERENCES `discussion_website`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_messages_ip_addresses1`
    FOREIGN KEY (`ip_id`)
    REFERENCES `discussion_website`.`ip_addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_czech_ci;


-- -----------------------------------------------------
-- Table `discussion_website`.`post_votes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discussion_website`.`post_votes` ;

CREATE TABLE IF NOT EXISTS `discussion_website`.`post_votes` (
  `user_id` INT(10) NOT NULL COMMENT '',
  `post_id` INT(10) NOT NULL COMMENT '',
  `vote` ENUM('like','hate') CHARACTER SET 'utf8' COLLATE 'utf8_czech_ci' NOT NULL COMMENT '',
  PRIMARY KEY (`user_id`, `post_id`)  COMMENT '',
  INDEX `fk_post_votes_posts1_idx` (`post_id` ASC)  COMMENT '',
  CONSTRAINT `fk_post_votes_posts1`
    FOREIGN KEY (`post_id`)
    REFERENCES `discussion_website`.`posts` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_post_votes_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `discussion_website`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_czech_ci;


-- -----------------------------------------------------
-- Table `discussion_website`.`post_images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discussion_website`.`post_images` ;

CREATE TABLE IF NOT EXISTS `discussion_website`.`post_images` (
  `post_id` INT(10) NOT NULL COMMENT '',
  `id` INT(10) NOT NULL COMMENT '',
  `name` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_czech_ci' NOT NULL COMMENT '',
  `approved` TINYINT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '',
  `showed` TINYINT(4) UNSIGNED NOT NULL DEFAULT '1' COMMENT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`post_id`, `id`)  COMMENT '',
  INDEX `fk_post_images_posts1_idx` (`post_id` ASC)  COMMENT '',
  CONSTRAINT `fk_post_images_posts1`
    FOREIGN KEY (`post_id`)
    REFERENCES `discussion_website`.`posts` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_czech_ci;


-- -----------------------------------------------------
-- Table `discussion_website`.`comment_images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discussion_website`.`comment_images` ;

CREATE TABLE IF NOT EXISTS `discussion_website`.`comment_images` (
  `post_id` INT(10) NOT NULL COMMENT '',
  `comment_id` INT(10) NOT NULL COMMENT '',
  `id` INT(10) NOT NULL COMMENT '',
  `name` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_czech_ci' NOT NULL COMMENT '',
  `approved` TINYINT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '',
  `showed` TINYINT(4) UNSIGNED NOT NULL DEFAULT '1' COMMENT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`post_id`, `comment_id`, `id`)  COMMENT '',
  INDEX `fk_comment_images_comments1_idx` (`post_id` ASC, `comment_id` ASC)  COMMENT '',
  CONSTRAINT `fk_comment_images_comments1`
    FOREIGN KEY (`post_id` , `comment_id`)
    REFERENCES `discussion_website`.`comments` (`post_id` , `id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_czech_ci;

USE `discussion_website` ;

-- -----------------------------------------------------
-- Placeholder table for view `discussion_website`.`identities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `discussion_website`.`identities` (`id` INT, `photo_id` INT, `email` INT, `nickname` INT, `gender` INT, `age` INT, `role` INT);

-- -----------------------------------------------------
-- View `discussion_website`.`identities`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `discussion_website`.`identities` ;
DROP TABLE IF EXISTS `discussion_website`.`identities`;
USE `discussion_website`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `identities` AS select `users`.`id` AS `id`,`users`.`photo_id` AS `photo_id`,`users`.`email` AS `email`,`users`.`nickname` AS `nickname`,`users`.`gender` AS `gender`,((year(now()) - year(`users`.`birthdate`)) - (date_format(now(),'%m%d') < date_format(`users`.`birthdate`,'%m%d'))) AS `age`,`users`.`role` AS `role` from `users`;
USE `discussion_website`;

DELIMITER $$

USE `discussion_website`$$
DROP TRIGGER IF EXISTS `discussion_website`.`user_images_auto_increment` $$
USE `discussion_website`$$
CREATE TRIGGER `user_images_auto_increment` BEFORE INSERT ON `user_images` FOR EACH ROW
BEGIN
    DECLARE max_id INT(10); 
SELECT `user_images`.`id` FROM `user_images` WHERE `user_images`.`user_id` = NEW.`user_id`
 ORDER BY `id` DESC LIMIT 1 INTO max_id;
    SET NEW.`id` = IF(ISNULL(max_id), 1, max_id + 1);
END$$


USE `discussion_website`$$
DROP TRIGGER IF EXISTS `discussion_website`.`comments_auto_increment` $$
USE `discussion_website`$$
CREATE TRIGGER `comments_auto_increment` BEFORE INSERT ON `comments` FOR EACH ROW
BEGIN
    DECLARE max_id INT(10); 
SELECT `comments`.`id` FROM `comments` WHERE `comments`.`post_id` = NEW.`post_id`
 ORDER BY `id` DESC LIMIT 1 INTO max_id;
    SET NEW.`id` = IF(ISNULL(max_id), 1, max_id + 1);
END$$


USE `discussion_website`$$
DROP TRIGGER IF EXISTS `discussion_website`.`messages_auto_increment` $$
USE `discussion_website`$$
CREATE TRIGGER `messages_auto_increment` BEFORE INSERT ON `messages` FOR EACH ROW
BEGIN
    DECLARE max_id INT(10); 
SELECT `messages`.`id` FROM `messages` WHERE `messages`.`user_id` = NEW.`recipient_id`
 ORDER BY `id` DESC LIMIT 1 INTO max_id;
    SET NEW.`id` = IF(ISNULL(max_id), 1, max_id + 1);
END$$


USE `discussion_website`$$
DROP TRIGGER IF EXISTS `discussion_website`.`post_images_auto_increment` $$
USE `discussion_website`$$
CREATE TRIGGER `post_images_auto_increment` BEFORE INSERT ON `post_images` FOR EACH ROW
BEGIN
    DECLARE max_id INT(10); 
SELECT `post_images`.`id` FROM `post_images` WHERE `post_images`.`post_id` = NEW.`post_id`
 ORDER BY `id` DESC LIMIT 1 INTO max_id;
    SET NEW.`id` = IF(ISNULL(max_id), 1, max_id + 1);
END$$


USE `discussion_website`$$
DROP TRIGGER IF EXISTS `discussion_website`.`comment_images_auto_increment` $$
USE `discussion_website`$$
CREATE TRIGGER `comment_images_auto_increment` BEFORE INSERT ON `comment_images` FOR EACH ROW
BEGIN
    DECLARE max_id INT(10); 
SELECT `comment_images`.`id` FROM `comment_images` WHERE `comment_images`.`comment_id` = NEW.`comment_id` AND `comment_images`.`post_id` = NEW.`post_id`
 ORDER BY `id` DESC LIMIT 1 INTO max_id;
    SET NEW.`id` = IF(ISNULL(max_id), 1, max_id + 1);
END$$

INSERT INTO `categories` VALUES (1,'social','Společenské'),(2,'professional','Odborné'),(3,'cultural','Kulturní');

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
